[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "candles"
version = "0.1.8"
description = "OCHL candle data processing library"
authors = [{name = "darren", email = "darren.the7@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "typing_extensions==4.14.0"
]

[project.urls]
Repository = "https://github.com/darren-the/python-packages"

[project.optional-dependencies]
test = ["pytest"]

[tool.pytest.ini_options]
testpaths = ["tests"]

[tool.setuptools.packages.find]
where = ["."]
include = ["candles*"]