[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taskgraph"
version = "0.1.1"
description = "Task orchestration framework"
authors = [{name = "darren", email = "darren.the7@gmail.com"}]
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.urls]
Homepage = "https://github.com/darren-the/crypto-trading-v3"
Repository = "https://github.com/darren-the/crypto-trading-v3"

[tool.setuptools]
packages = ["taskgraph"]