FROM mcr.microsoft.com/devcontainers/python:3.11-bullseye

USER vscode

# RUN python -m pip install --user poetry
ENV PATH="/home/vscode/.local/bin:$PATH"
# RUN poetry config virtualenvs.in-project true
# RUN poetry --version && python --version
